services:
  # API Service
  - type: web
    name: luu-sac-api
    runtime: node
    region: oregon
    plan: free
    buildCommand: bash scripts/build-api.sh
    startCommand: cd apps/api && node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://luu-sac-web.onrender.com
      - key: CLOUDINARY_CLOUD_NAME
        value: dnm1hfesq
      - key: CLOUDINARY_API_KEY
        value: 644752233173812
      - key: CLOUDINARY_API_SECRET
        value: VsCT_PMJpRj5hirtblH7D-CRsHk
      - key: PAYOS_CLIENT_ID
        value: d05dfd7d-9da1-4632-812a-7278316af30a
      - key: PAYOS_API_KEY
        value: e8d436fd-0364-45ce-8caf-15c2ec64cf66
      - key: PAYOS_CHECKSUM_KEY
        value: e43cad73fa0f4347b038d64dcd06cda1399f7c3e718a952d9049f2d8c82e7141
    healthCheckPath: /

  # Web Service
  - type: web
    name: luu-sac-web
    runtime: node
    region: oregon
    plan: free
    buildCommand: bash scripts/build-web.sh
    startCommand: cd apps/web && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://luu-sac-api.onrender.com/api
